In [1]:
import torch
import torch.nn as nn

In [2]:
# pool of square window of size=3, stride=2
m = nn.MaxPool2d(3, stride=2)
# pool of non-square window
m = nn.MaxPool2d((3, 2), stride=(2, 1))
input = torch.randn(20, 16, 50, 32)
output = m(input)


In [4]:
output.shape

torch.Size([20, 16, 24, 31])

In [6]:
from unet.unet_parts import *

In [14]:
m = nn.MaxPool2d(2)

In [15]:
m(torch.rand(32,1,572,572)).shape

torch.Size([32, 1, 286, 286])

In [19]:
m.padding

0

In [123]:
n = nn.Conv2d(1,2,2)

In [25]:
x = list(n.parameters())

In [28]:
y = x[0]

In [29]:
y.shape

torch.Size([2, 1, 2, 2])

In [132]:
t = torch.rand(1,568,568,requires_grad=True)

In [133]:
yt = n(t)

In [134]:
l = torch.sum(yt)

In [135]:
l.backward()

In [136]:
t.grad

tensor([[[-0.4872, -0.5021, -0.5021,  ..., -0.5021, -0.5021, -0.0149],
         [-0.3476, -0.7163, -0.7163,  ..., -0.7163, -0.7163, -0.3688],
         [-0.3476, -0.7163, -0.7163,  ..., -0.7163, -0.7163, -0.3688],
         ...,
         [-0.3476, -0.7163, -0.7163,  ..., -0.7163, -0.7163, -0.3688],
         [-0.3476, -0.7163, -0.7163,  ..., -0.7163, -0.7163, -0.3688],
         [ 0.1396, -0.2142, -0.2142,  ..., -0.2142, -0.2142, -0.3539]]])

In [66]:
p = torch.rand(1,3,3)

In [67]:
norm_weights = torch.zeros(t.shape)


In [68]:
padding = 0

In [70]:
kernel_size = 3

In [71]:
for r in range(p.shape[-2]):
    for c in range(p.shape[-1]):
        norm_weights[max(0,r-padding):t.shape[-2]-(kernel_size-1)+padding+r,max(0,c-padding):t.shape[-1]-(kernel_size-1)+padding+c] += p[0,r,c]**2

In [72]:
norm_weights

tensor([[0.3997, 0.4012, 0.9858,  ..., 0.9858, 0.5860, 0.5845],
        [0.8605, 0.8693, 1.5417,  ..., 1.5417, 0.6812, 0.6724],
        [1.4966, 2.3680, 3.7157,  ..., 3.7157, 2.2191, 1.3477],
        ...,
        [1.4966, 2.3680, 3.7157,  ..., 3.7157, 2.2191, 1.3477],
        [1.0969, 1.9668, 2.7299,  ..., 2.7299, 1.6330, 0.7632],
        [0.6361, 1.4987, 2.1739,  ..., 2.1739, 1.5379, 0.6753]])

In [73]:
p

tensor([[[0.6322, 0.0387, 0.7646],
         [0.6788, 0.0853, 0.2965],
         [0.7976, 0.9288, 0.8217]]])

In [74]:
p**2

tensor([[[0.3997, 0.0015, 0.5845],
         [0.4608, 0.0073, 0.0879],
         [0.6361, 0.8626, 0.6753]]])

In [110]:
p2 = p**2

In [111]:
p3 = p**2

In [112]:
for r in range(p2.shape[-2]-1):
    p2[:,r+1:,:] += p3[:,r,:]


In [113]:
p2

tensor([[[0.3997, 0.0015, 0.5845],
         [0.8605, 0.0088, 0.6724],
         [1.4966, 0.8714, 1.3477]]])

In [114]:
for c in range(p2.shape[-1]-1):
    print(p2[:, :, c].unsqueeze(-1))
    p2[:,:,c+1:] += p3[:,:,c].unsqueeze(-1)

tensor([[[0.3997],
         [0.8605],
         [1.4966]]])
tensor([[[0.4012],
         [0.4696],
         [1.5075]]])


In [115]:
p2

tensor([[[0.3997, 0.4012, 0.9858],
         [0.8605, 0.4696, 1.1405],
         [1.4966, 1.5075, 2.8464]]])

In [118]:
len(list(n.parameters()))

2

In [121]:
x[1].shape

torch.Size([128])

In [122]:
n

[Parameter containing:
 tensor([[[[-1.4838e-02, -1.6087e-03, -3.8317e-02],
           [ 5.7875e-03, -1.1970e-02, -3.3199e-02],
           [-9.5730e-03,  1.7141e-02, -1.0084e-02]],
 
          [[-9.6628e-03,  2.7475e-02,  3.2139e-02],
           [-1.7199e-02,  1.5689e-02,  3.5995e-02],
           [ 2.0935e-02,  6.3503e-03,  7.2908e-05]],
 
          [[ 1.2676e-02, -1.5422e-02,  1.5394e-02],
           [-7.9797e-03, -3.1373e-04,  3.5750e-02],
           [-2.4574e-02, -1.6500e-02,  1.3587e-02]],
 
          ...,
 
          [[ 2.9406e-02, -2.4247e-02,  2.8160e-02],
           [-2.3505e-02,  3.1415e-02, -3.8957e-02],
           [ 3.6200e-02, -1.8891e-02,  2.6441e-02]],
 
          [[ 1.6197e-02, -2.2831e-02, -3.1759e-02],
           [ 2.9770e-02, -3.2076e-02, -1.1686e-02],
           [-9.5670e-03, -9.1462e-03,  2.8900e-02]],
 
          [[-1.4828e-02,  3.4142e-02, -7.9878e-03],
           [ 2.9130e-02,  3.2098e-02,  3.5676e-02],
           [-2.4853e-02,  3.7711e-02, -2.0446e-02]]],
 
 
   